=== sabrown256/pactnew/sx/tests/txml2.dtd
<?xml version="1.0"?>

<!ELEMENT types (float*, int*)>

<!ELEMENT float (ord, sz, eb, mb)>
<!ELEMENT ord (#PCDATA)>
<!ELEMENT sz  (#PCDATA)>
<!ELEMENT eb  (#PCDATA)>
<!ELEMENT mb  (#PCDATA)>

<!ELEMENT int EMPTY>
<!ATTLIST int
   ord (normal | reverse) #REQUIRED
   sz  (1 | 2 | 4 | 8)    #REQUIRED
>

=== sabrown256/pactnew/sx/tests/txml2.xml
<?xml version="1.0"?>
<!DOCTYPE types SYSTEM "txml2.dtd">

<!-- ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ -->
<!-- ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ -->

<types>
   <float>
      <ord>normal</ord>
      <sz>4</sz>
      <eb>8</eb>
      <mb>23</mb>
   </float> 

   <float>
      <ord>reverse</ord>
      <sz>4</sz>
      <eb>8</eb>
      <mb>23</mb>
   </float> 

   <int ord='normal' sz='4' />
</types>
